Lab 1_2
JokerJudge/PY200 pull request #2
Opened 2020-02-24 09:27 UTC by JokerJudge

2020-02-25 19:30 UTC, aeksei requested changes
Надо обязательно подправить форматирование строк, и решить вопрос со слабыми ссылками

2020-02-25 19:30 UTC, aeksei commented on lab/py200_lab_1_1.py
> +#from weakref import ref
Необходимо добавить слабые ссылки, когда ссылаемся на либо на следующую ноду, либо на предыдущую

2020-02-25 19:30 UTC, aeksei commented on lab/py200_lab_1_2(Date).py
> +            month = self.__month
оооуу)) это совсем не спортивно)) есть же чудо форматирование строк
например так можно оформить `f"{self.__day:0>2} ..."`
https://docs.python.org/3/library/string.html#format-specification-mini-language

Это надо срочно переделать, чтобы никто не увидел)))

2020-02-25 19:30 UTC, aeksei commented on lab/py200_lab_1_2(Date).py
> +    def __init__(self, *args):
Есть проверки для свойства `date`, они немного пересекаются с тем что в `__init__`
Плюс отдельно проверки для `day, month, year`. Много разнородных мест, где сидят проверки.
В идеале попробовать оставить по отдельности проверки в `day, month, year`, а потом, если не будет исключений, проверить их вместе в `is_valid_date`. Но в любом случае эту схему надо допиливать не факт, что она будет сходу работать

2020-02-25 21:04 UTC, JokerJudge commented on lab/py200_lab_1_2(Date).py
> +        return f'{self.__day:0>2}.{self.__month:0>2}.{self.__year}'
Готово! Этот момент исправил

2020-02-26 09:22 UTC, aeksei commented on lab/py200_lab_1_2(Date).py
> +        return f'{self.__day:0>2}.{self.__month:0>2}.{self.__year}'
Отлично, лабораторная с датами зачтена

2020-02-26 09:25 UTC, aeksei approved these changes
Лабораторная с Date зачтена. Слабые ссылки надо сделать

2020-02-26 20:11 UTC, merged