lab 2 is done
JokerJudge/PY200 pull request #3
Opened 2020-02-24 12:52 UTC by JokerJudge

2020-02-25 19:38 UTC, aeksei requested changes
Скорректируйте `__init__` и вопросов по нет))

2020-02-25 19:38 UTC, aeksei commented on lab/figures.py
> +            d.append(temp)
ну тут бы я обошелся таким способом:
`d.append({"x": c_x, "y": c_y})`

2020-02-25 19:38 UTC, aeksei commented on lab/figures.py
> +        self.d = d # список словарей - пример: [{'x': 1, 'y': 2}, {'x': 5, 'y': 6}, {'x': 7, 'y': 4}]
А вообще в идеале:
`self.d = [{"x": c_x, "y": c_y} for for c_x, c_y in args]`

2020-02-25 21:13 UTC, JokerJudge commented on lab/figures.py
> +
Исправлено. Выглядит очень лаконично и без создания лишних переменных

2020-02-26 09:26 UTC, aeksei approved these changes
По лабораторной с фигурами тоже вопросов больше нет. Можете сливать

2020-02-26 20:12 UTC, merged